# Specifies a gem mirror; duplicated in acceptance setup
# to ensure a similar environment on acceptance hosts.
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

def location_for(place, fake_version = nil)
  if place =~ /^(git:[^#]*)#(.*)/
    [fake_version, { :git => $1, :branch => $2, :require => false }].compact
  elsif place =~ /^file:\/\/(.*)/
    ['>= 0', { :path => File.expand_path($1), :require => false }]
  else
    [place, { :require => false }]
  end
end

gem "beaker", :git => 'https://github.com/MosesMendoza/beaker', :ref => '0f4f882b0f82d186ae05f1e2c3a3801730a17e87'
gem "beaker-hostgenerator", *location_for(ENV['BEAKER_HOSTGENERATOR_VERSION'] || "~> 0.3")
gem "rake", "~> 10.1"
gem "httparty", :require => false
gem 'uuidtools', :require => false

group(:test) do
  gem "rspec", "~> 2.14.0", :require => false
  gem "mocha", "~> 0.10.5", :require => false
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
